In [1]:
#imports
import numpy as np

In [2]:
#create a vector
nv = np.array([ [1,2,3,4] ])
print(nv)

[[1 2 3 4]]


In [3]:
#transpose above vector
print(nv.T)

[[1]
 [2]
 [3]
 [4]]


In [11]:
#transpose the transpose
nvT = nv.T
print(nvT)

[[1]
 [2]
 [3]
 [4]]


In [4]:
#repeat for matrix
nM = np.array([ [1,2,3,4],[5,6,7,8] ])
print(nM)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#transponse matrix
print(nM.T) 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
#transpose the transpose
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
