In [2]:
import numpy as np

In [8]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

In [12]:
print(A), print(' ')
print(B), print(' ')
print(C), print(' ')

[[ 0.38525641 -0.24928838 -1.3180497   0.79023354]
 [-0.30915514 -0.10330807  1.57244303 -0.63326273]
 [ 0.20291824 -1.17746785  0.67699299  0.45286705]]
 
[[ 1.31099305  1.41608882  0.21279173  0.0817738  -0.33707876]
 [ 0.38070622 -2.1104656  -0.79929066  0.40740686  0.31557055]
 [-2.02061246  0.05725326 -0.85524284 -2.23657956 -0.69081806]
 [ 0.16956113 -0.41950201 -0.22452445 -0.14768193  1.58512118]]
[[-1.05866003 -1.9473732  -1.09554752 -1.31572083  0.30857229  0.36656364
  -1.76745353]
 [-0.35307701 -0.12019978 -1.69262361 -1.73779798  0.20596476  0.93238926
   0.24107054]
 [ 0.20268485  1.48613593 -1.17757828  0.28324766  0.47361105 -0.52558625
  -0.64751777]]


In [16]:
#try some multiplication
# print(np.round( A@B, 2)), print(' ')
# print(np.round( A@C , 2)), print(' ')
# print(np.round( B@C , 2)), print(' ')
print(np.round( C.T@A, 2)), print(' ')

#Here, c and a cannot be multiplied as the inner dimensions are different. We can get around this by first transposing C. Now, the new matrix dimensions are 7 by 4


[[-0.26  0.06  0.98 -0.52]
 [-0.41 -1.25  3.38 -0.79]
 [-0.14  1.83 -2.01 -0.33]
 [ 0.09  0.17 -0.81  0.19]
 [ 0.15 -0.66  0.24  0.33]
 [-0.25  0.43  0.63 -0.54]
 [-0.89  1.18  2.27 -1.84]]
 


(None, None)

In [ ]:
#It is important to remember the rul for matrix multiplication validity