In [4]:
import numpy as np

In [2]:
#create a vector
v = np.array([1,40,2,-3])

#find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min, max: %g,%g' %(minval, maxval))

Min, max: -3,40


In [10]:
#argmin, argmax values
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')
print(f'Min val is {v[minidx]}, max val is {v[maxidx]}')


Min,max indices: 3,1
 
Min val is -3, max val is 40


In [21]:
# w/ matrices
M = np.array([
    [7,1,0],
    [20,8,5]7
])

print(M)

#various minima within this matrix
minvals1 = np.min(M)           # minimum from entire matrix
minvals2 = np.min(M,axis=0) # minimum from each column (across rows)
minvals3 = np.min(M,axis=1) # minimum from each row (across columns)
print('')

print(minvals1)
print(minvals2)
print(minvals3)

[[ 7  1  0]
 [20  8  5]]

0
[7 1 0]
[0 5]
